In [1]:
## IMPORTS 
import evotoon
from data_classes import CatParam, IntParam, FloatParam


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
#import seaborn as sns#

import random

import warnings
warnings.filterwarnings("ignore")

In [2]:
## MAKE SEED
SEED = evotoon.make_seed(765)
separator = "--------------------------------------------------------"

In [3]:
## EXAMPLE WITH CodGA

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("p_c", 0.001, 1, 3),
	FloatParam("p_m", 0.001, 1, 3),
]
int_params = [
	IntParam("N", 1, 50),
]

all_params = float_params + int_params 
all_params = {param.name: param for param in all_params}



initial_batch = evotoon.initialization(poblation_size, float_params, int_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
path = "./InstanciasNKLandscapes/Instances-Training"
n = 10

instance_list = evotoon.choose_instances(path, n , SEED)

instance_list, seed_list = evotoon.select_seeds(instance_list, n, SEED)

print(separator, "Instances running and seeds", separator)
for ins,seed in zip(instance_list,seed_list):
	print("instance:", ins, "seed:", seed)

function_kwargs = {
	"executable_path": "./CodGA/ga-nk",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"output": "xd.txt",
	"t_max": 1000 
}

print(pd.DataFrame(initial_batch))

-------------------------------------------------------- Instances running and seeds --------------------------------------------------------
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 766
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 767
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 768
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 769
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 770
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 771
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 772
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 773
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 774
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 765
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 766

In [4]:
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_CodGA, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

Total Budget: 4750
Budget left 4750
------------------------------------------------------------------------------------------------
Budget left 4500
------------------------------------------------------------------------------------------------
Budget left 4250
------------------------------------------------------------------------------------------------
Budget left 4000
------------------------------------------------------------------------------------------------
Budget left 3750
------------------------------------------------------------------------------------------------
Budget left 3500
------------------------------------------------------------------------------------------------
Budget left 3250
------------------------------------------------------------------------------------------------
Budget left 3000
------------------------------------------------------------------------------------------------
Budget left 2750
------------------------------------------------------------------------------------------------
Budget left 2500
------------------------------------------------------------------------------------------------
Budget left 2250
------------------------------------------------------------------------------------------------
Budget left 2000
------------------------------------------------------------------------------------------------
Budget left 1750
------------------------------------------------------------------------------------------------
Budget left 1500
------------------------------------------------------------------------------------------------
Budget left 1250
------------------------------------------------------------------------------------------------
Budget left 1000
------------------------------------------------------------------------------------------------
Budget left 750
------------------------------------------------------------------------------------------------
Budget left 500
------------------------------------------------------------------------------------------------
Budget left 250
------------------------------------------------------------------------------------------------

      p_c    p_m     N  Step_Found  VALUE
0   0.710  0.142   5.0          19   11.0
23  0.458  0.570   6.0          18   17.2
16  0.800  0.083  19.0          18   19.8
10  0.915  0.083  37.0           3   23.2
17  0.673  0.935   7.0          17   23.2
43  0.116  0.151  13.0          13   24.6
40  0.872  0.691  13.0          16   34.0
8   0.864  0.436   6.0          15   36.6
13  0.946  0.151  23.0          14   37.2
37  0.111  0.728  16.0          16   40.8
31  0.762  0.323  20.0           5   44.0
45  0.879  0.760  44.0           6   44.6
18  0.223  0.594   6.0          19   46.6
41  0.283  0.811  22.0          19   53.0
48  0.667  0.390   7.0          19   59.0
49  0.864  0.792   6.0          16   62.6
1   0.271  0.935   7.0           5   66.8
3   0.762  0.906  30.0          17   68.8
27  0.834  0.050  20.0          18   72.0
21  0.915  0.083  13.0          19   74.2
20  0.548  0.096  27.0          16   74.8
47  0.506  0.744  15.0          10   89.6
11  0.862  0.366  17.0           8   90.8
33  0.621  0.880   9.0          19   98.8
39  0.948  0.728  29.0          18  103.6
6   0.164  0.910  16.0          12  111.0
30  0.873  0.744  26.0           3  116.4
32  0.926  0.188  25.0          19  119.6
14  0.472  0.482  20.0          11  120.2
28  0.277  0.863  22.0          14  121.2
38  0.817  0.880  20.0          15  132.6
46  0.555  0.880   1.0          12  134.0
25  0.212  0.570  16.0          15  142.8
36  0.555  0.880  20.0          14  144.8
24  0.399  0.919  24.0          15  152.2
44  0.613  0.285  34.0          17  155.6
22  0.262  0.918  30.0          18  157.6
2   0.550  0.240  20.0          16  167.8
29  0.702  0.096  15.0          18  168.6
19  0.332  0.880  34.0          17  172.2
5   0.193  0.811  22.0          12  192.8
9   0.686  0.265   9.0          14  195.0
15  0.665  0.722  21.0          14  223.2
34  0.555  0.381   5.0          19  225.0
35  0.419  0.918  10.0          17  243.8
12  0.646  0.906  30.0          19  255.2
26  0.719  0.811  22.0          17  284.8
7   0.838  0.732  36.0          17  388.8
42  0.872  0.074   6.0          19  400.2
4   0.864  0.251   6.0          19  413.4

In [2]:
## MAKE SEED
SEED = evotoon.make_seed(283)
separator = "--------------------------------------------------------"
## EXAMPLE WITH CodGA

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("p_c", 0.001, 1, 3),
	FloatParam("p_m", 0.001, 1, 3),
]
int_params = [
	IntParam("N", 1, 50),
]

all_params = float_params + int_params 
all_params = {param.name: param for param in all_params}



initial_batch = evotoon.initialization(poblation_size, float_params, int_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
path = "./InstanciasNKLandscapes/Instances-Training"
n = 10

instance_list = evotoon.choose_instances(path, n , SEED)

instance_list, seed_list = evotoon.select_seeds(instance_list, n, SEED)

print(separator, "Instances running and seeds", separator)
for ins,seed in zip(instance_list,seed_list):
	print("instance:", ins, "seed:", seed)

function_kwargs = {
	"executable_path": "./CodGA/ga-nk",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"output": "xd.txt",
	"t_max": 1000 
}

print(pd.DataFrame(initial_batch))
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_CodGA, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

-------------------------------------------------------- Instances running and seeds --------------------------------------------------------
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 284
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 285
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 286
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 287
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 288
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 289
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 290
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 291
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 292
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 283
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 284

      p_c    p_m     N  Step_Found  VALUE
5   0.790  0.397  33.0           8    2.8
8   0.056  0.405  34.0           1    9.2
7   0.529  0.240  39.0          10   10.4
33  0.449  0.079  23.0          11   10.8
28  0.356  0.849  31.0          17   18.6
44  0.962  0.200  18.0          19   21.2
48  0.489  0.473  12.0          19   22.2
16  0.601  0.893  25.0           8   23.4
12  0.824  0.612   6.0          16   31.6
9   0.106  0.845  18.0          11   31.8
37  0.973  0.045  44.0          16   33.8
14  0.251  0.240  49.0          12   37.6
30  0.523  0.404  13.0          18   37.8
32  0.778  0.194  12.0          19   43.8
2   0.356  0.755  35.0          10   55.6
38  0.280  0.327  38.0          14   63.0
45  0.340  0.516  18.0          19   64.4
10  0.832  0.131  31.0          12   68.4
4   0.923  0.047  38.0          17   69.8
27  0.597  0.563   8.0          13   70.0
40  0.790  0.164  45.0          17   71.8
15  0.361  0.675  34.0           0   78.0
3   0.340  0.200  18.0          18   80.6
20  0.765  0.511  12.0          17   89.6
17  0.615  0.850  15.0          14   93.8
41  0.356  0.705  35.0          15   97.6
0   0.778  0.194  22.0          12   98.6
24  0.356  0.070  35.0          18   98.6
13  0.956  0.285   4.0          10  102.4
35  0.701  0.527   4.0          18  105.4
49  0.971  0.824  37.0          19  122.4
6   0.983  0.329  10.0          15  124.0
31  0.096  0.473  44.0          18  128.0
29  0.106  0.200  18.0           8  140.2
25  0.506  0.959  47.0          15  142.6
1   0.251  0.240  37.0          15  142.8
22  0.838  0.429  39.0          17  196.2
11  0.681  0.415  16.0          11  199.4
43  0.733  0.866  20.0          13  206.4
26  0.167  0.053  34.0           3  209.6
19  0.823  0.285  26.0          18  212.8
21  0.733  0.866  23.0           9  216.0
42  0.790  0.267  43.0           0  223.8
34  0.361  0.866  35.0          16  233.6
39  0.231  0.288   2.0          14  242.0
46  0.671  0.443  32.0          19  267.8
18  0.096  0.473  25.0           0  316.2
47  0.251  0.240  30.0          19  317.2
23  0.119  0.554  30.0          10  338.0
36  0.361  0.675  38.0          18  466.0

In [3]:
## MAKE SEED
SEED = evotoon.make_seed(315)
separator = "--------------------------------------------------------"
## EXAMPLE WITH CodGA

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("p_c", 0.001, 1, 3),
	FloatParam("p_m", 0.001, 1, 3),
]
int_params = [
	IntParam("N", 1, 50),
]

all_params = float_params + int_params 
all_params = {param.name: param for param in all_params}



initial_batch = evotoon.initialization(poblation_size, float_params, int_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
path = "./InstanciasNKLandscapes/Instances-Training"
n = 10

instance_list = evotoon.choose_instances(path, n , SEED)

instance_list, seed_list = evotoon.select_seeds(instance_list, n, SEED)

print(separator, "Instances running and seeds", separator)
for ins,seed in zip(instance_list,seed_list):
	print("instance:", ins, "seed:", seed)

function_kwargs = {
	"executable_path": "./CodGA/ga-nk",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"output": "xd.txt",
	"t_max": 1000 
}

print(pd.DataFrame(initial_batch))
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_CodGA, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

-------------------------------------------------------- Instances running and seeds --------------------------------------------------------
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 316
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 317
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 318
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 319
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 320
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 321
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 322
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 323
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 324
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 315
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 316

      p_c    p_m     N  Step_Found  VALUE
14  0.901  0.147  33.0           0   11.8
24  0.397  0.131  10.0           9   14.2
6   0.164  0.925  37.0           4   16.6
38  0.567  0.382  17.0          15   19.2
11  0.954  0.854  10.0          16   19.6
25  0.637  0.147  33.0          13   25.2
20  0.328  0.104  14.0          16   27.4
33  0.206  0.389  35.0          18   29.8
17  0.926  0.477  50.0          18   31.0
28  0.935  0.124  15.0          11   32.4
0   0.328  0.104  16.0          12   37.4
16  0.959  0.050  32.0          12   38.0
47  0.672  0.050  32.0           0   43.8
26  0.028  0.854  10.0          19   44.0
2   0.462  0.469  14.0          12   48.0
22  0.205  0.947  18.0          19   51.0
9   0.321  0.041  38.0           7   64.8
7   0.056  0.279   1.0          18   70.0
40  0.926  0.477  22.0          17   72.8
32  0.935  0.171  32.0          12   75.0
43  0.309  0.315  35.0          19   79.8
41  0.634  0.564  30.0          19   84.8
42  0.594  0.393  24.0          19   87.2
15  0.959  0.050  24.0          14   87.8
36  0.156  0.477  22.0          16   88.6
10  0.569  0.083  10.0           2  101.6
21  0.473  0.118  10.0          18  102.6
37  0.145  0.347  12.0          16  111.4
5   0.426  0.116  18.0           4  119.2
30  0.928  0.116  18.0          16  125.8
19  0.462  0.469  30.0           1  131.0
4   0.150  0.708  32.0          19  131.4
27  0.204  0.397  32.0          14  133.2
18  0.549  0.050  24.0          19  136.0
45  0.328  0.712  45.0          17  143.6
23  0.995  0.621  36.0          19  159.0
49  0.519  0.655   7.0          18  176.4
46  0.195  0.332  33.0          17  180.2
31  0.293  0.734  12.0          15  182.0
12  0.106  0.131  36.0          18  192.8
8   0.482  0.219  44.0           3  194.6
1   0.672  0.207  23.0          14  213.0
13  0.602  0.279   1.0          17  215.2
48  0.156  0.477  25.0           8  221.6
3   0.150  0.366  32.0          15  249.6
44  0.569  0.083  12.0          15  254.6
35  0.813  0.118  10.0          19  259.0
34  0.060  0.032  33.0           9  275.4
39  0.622  0.601  13.0          18  301.2
29  0.696  0.521  11.0          14  353.6

In [4]:
## MAKE SEED
SEED = evotoon.make_seed(39)
separator = "--------------------------------------------------------"
## EXAMPLE WITH CodGA

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("p_c", 0.001, 1, 3),
	FloatParam("p_m", 0.001, 1, 3),
]
int_params = [
	IntParam("N", 1, 50),
]

all_params = float_params + int_params 
all_params = {param.name: param for param in all_params}



initial_batch = evotoon.initialization(poblation_size, float_params, int_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
path = "./InstanciasNKLandscapes/Instances-Training"
n = 10

instance_list = evotoon.choose_instances(path, n , SEED)

instance_list, seed_list = evotoon.select_seeds(instance_list, n, SEED)

print(separator, "Instances running and seeds", separator)
for ins,seed in zip(instance_list,seed_list):
	print("instance:", ins, "seed:", seed)

function_kwargs = {
	"executable_path": "./CodGA/ga-nk",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"output": "xd.txt",
	"t_max": 1000 
}

print(pd.DataFrame(initial_batch))
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_CodGA, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

-------------------------------------------------------- Instances running and seeds --------------------------------------------------------
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 43
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 44
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 45
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 46
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 47
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 48
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 39
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 40
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 41
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 42
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 43

      p_c    p_m     N  Step_Found  VALUE
25  0.697  0.290   2.0           4    6.6
0   0.292  0.290   4.0          18   17.4
21  0.980  0.437  18.0          14   18.0
13  0.643  0.276   3.0          16   26.8
15  0.989  0.537  10.0           9   27.0
1   0.446  0.888  24.0          18   29.4
10  0.977  0.209  25.0          19   31.4
12  0.207  0.532  48.0          18   33.4
32  0.293  0.560   3.0          17   34.4
36  0.372  0.143  12.0          19   35.8
14  0.437  0.116   5.0           3   38.4
47  0.466  0.271  42.0           3   38.8
2   0.686  0.290   4.0          17   46.0
45  0.616  0.105   8.0          18   48.8
6   0.170  0.668  25.0          17   49.0
37  0.008  0.262  39.0          17   50.2
41  0.446  0.262  13.0          17   52.0
27  0.054  0.181  43.0          19   55.4
30  0.298  0.373   8.0          19   56.4
19  0.877  0.594  10.0          19   56.4
3   0.644  0.891  40.0          10   57.8
42  0.871  0.656  22.0          18   58.2
24  0.360  0.430   3.0          19   58.8
23  0.130  0.188   8.0           5   63.0
38  0.687  0.738  18.0          16   63.6
4   0.347  0.692  46.0          18   64.8
40  0.446  0.262  39.0          15   65.4
18  0.597  0.594   9.0          18   71.4
48  0.781  0.074  37.0          19   74.2
7   0.531  0.165  36.0          19   78.8
8   0.572  0.968  32.0          16   80.0
22  0.721  0.446  47.0          11   86.0
46  0.523  0.042  36.0           4   94.4
9   0.286  0.631  37.0          17   94.6
43  0.882  0.430   2.0          13  108.2
39  0.372  0.131  12.0          16  128.0
5   0.519  0.081  22.0          15  131.0
17  0.416  0.496   3.0          15  134.2
11  0.558  0.186  22.0          18  137.4
26  0.963  0.802  29.0           6  150.2
33  0.104  0.223  10.0          18  164.4
49  0.525  0.262  11.0          19  175.0
35  0.616  0.235  40.0          17  181.4
20  0.640  0.738  18.0          19  210.2
16  0.580  0.808  50.0          14  210.6
34  0.558  0.250  22.0          16  221.2
31  0.142  0.776  40.0          12  228.2
29  0.543  0.236  16.0          14  230.6
44  0.054  0.368  43.0          12  317.4
28  0.388  0.749  47.0          14  353.4

In [5]:
## MAKE SEED
SEED = evotoon.make_seed(346)
separator = "--------------------------------------------------------"
## EXAMPLE WITH CodGA

# Env configuration
poblation_size = 50

# Parameter settings
float_params = [
	FloatParam("p_c", 0.001, 1, 3),
	FloatParam("p_m", 0.001, 1, 3),
]
int_params = [
	IntParam("N", 1, 50),
]

all_params = float_params + int_params 
all_params = {param.name: param for param in all_params}



initial_batch = evotoon.initialization(poblation_size, float_params, int_params)

# Tuner parameters

update_cycle = 5
budget = 5000

# SET ENVIRONMENT FOR THE ACO ALGORITHM TO TUNE
path = "./InstanciasNKLandscapes/Instances-Training"
n = 10

instance_list = evotoon.choose_instances(path, n , SEED)

instance_list, seed_list = evotoon.select_seeds(instance_list, n, SEED)

print(separator, "Instances running and seeds", separator)
for ins,seed in zip(instance_list,seed_list):
	print("instance:", ins, "seed:", seed)

function_kwargs = {
	"executable_path": "./CodGA/ga-nk",
	"instance_list": instance_list,
	"seed_list": seed_list,
	"output": "xd.txt",
	"t_max": 1000 
}

print(pd.DataFrame(initial_batch))
evotoon.evo_tunning(all_params=all_params, float_params=float_params, int_params=int_params, budget=budget, poblation_size=poblation_size, initial_batch=initial_batch, execute_algorithm=evotoon.execute_CodGA, returning_type="ABSOLUTE_OPTIMAL_DIFF", **function_kwargs)

-------------------------------------------------------- Instances running and seeds --------------------------------------------------------
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.1 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.2 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.3 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.4 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_20/nk_20_2.5 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.1 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.2 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.3 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.4 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_38/nk_38_2.5 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.1 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.2 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.3 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.4 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_2_52/nk_52_2.5 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.1 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.2 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.3 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.4 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_20/nk_20_3.5 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.1 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.2 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.3 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 347
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 348
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 349
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 350
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 351
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 352
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 353
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 354
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.4 seed: 355
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 346
instance: ./InstanciasNKLandscapes/Instances-Training/nk_3_34/nk_34_3.5 seed: 347

      p_c    p_m     N  Step_Found  VALUE
37  0.922  0.322  11.0          18    9.4
11  0.826  0.220  43.0          18   11.6
5   0.329  0.883  35.0           7   13.4
42  0.864  0.883  17.0          15   15.8
41  0.008  0.102  15.0          17   19.4
19  0.676  0.215  41.0          14   19.4
17  0.494  0.244  12.0          13   20.6
29  0.319  0.244  39.0          11   23.0
0   0.826  0.586  43.0           1   24.0
24  0.963  0.883  33.0          11   32.4
6   0.493  0.639  46.0          15   34.0
39  0.717  0.883   9.0          12   35.2
1   0.100  0.610  42.0           4   36.2
32  0.949  0.282  15.0          16   41.4
40  0.329  0.344  29.0          19   42.0
28  0.582  0.322  11.0          17   43.8
21  0.807  0.836  20.0          17   53.6
22  0.776  0.244  12.0           1   54.8
7   0.008  0.102   6.0          18   55.4
10  0.457  0.423  10.0          12   58.0
13  0.824  0.891  28.0           9   62.0
27  0.436  0.789   2.0          19   62.6
9   0.255  0.198   7.0           7   68.8
18  0.998  0.883  33.0           0   71.2
12  0.717  0.112  26.0          12   73.4
48  0.717  0.232  47.0           8   80.8
33  0.335  0.549  33.0           4   81.2
16  0.717  0.127  33.0          14   91.4
25  0.642  0.610  42.0          11   93.8
8   0.668  0.721  33.0          12  108.6
36  0.727  0.224  41.0          17  109.6
47  0.573  0.940  38.0          19  114.2
20  0.820  0.331   1.0          17  129.4
14  0.749  0.470   6.0          19  129.8
44  0.717  0.232  33.0          17  135.0
43  0.421  0.112  19.0          15  136.6
15  0.405  0.883  35.0          12  148.4
34  0.567  0.089  17.0          18  174.6
3   0.645  0.789  26.0          11  176.6
38  0.963  0.025  33.0          13  202.6
31  0.666  0.883   9.0          19  207.6
30  0.941  0.318  46.0          19  207.8
35  0.717  0.868  26.0          13  222.0
49  0.744  0.940  10.0          17  239.0
26  0.576  0.912  30.0          13  244.2
23  0.260  0.244  12.0           9  244.8
4   0.101  0.291  39.0           8  261.4
2   0.839  0.322  11.0           1  274.8
46  0.493  0.232   6.0          19  289.8
45  0.169  0.956  33.0          19  318.4

In [10]:


instance_list = [
	"./ALL_tsp/eil76.tsp",
	"./ALL_tsp/lin318.tsp",
	"./ALL_tsp/pr107.tsp",
	"./ALL_tsp/kroD100.tsp",
	"./ALL_tsp/d1291.tsp",
	"./ALL_tsp/pr1002.tsp",
	"./ALL_tsp/vm1084.tsp",
	"./ALL_tsp/pr299.tsp",
	"./ALL_tsp/u2319.tsp",
	"./ALL_tsp/tsp225.tsp",
	"./ALL_tsp/st70.tsp",
	"./ALL_tsp/rat783.tsp",
	"./ALL_tsp/fnl4461.tsp",
	"./ALL_tsp/kroA100.tsp",
	"./ALL_tsp/bier127.tsp",
	"./ALL_tsp/pr2392.tsp",
	"./ALL_tsp/pr144.tsp",
	"./ALL_tsp/d198.tsp",
	"./ALL_tsp/kroA200.tsp",
	"./ALL_tsp/berlin52.tsp",
	"./ALL_tsp/pcb442.tsp",
	"./ALL_tsp/fl1400.tsp",
	"./ALL_tsp/att532.tsp",
	"./ALL_tsp/pr439.tsp",
	"./ALL_tsp/rat195.tsp",
	"./ALL_tsp/ch130.tsp",
	"./ALL_tsp/pcb3038.tsp",
	"./ALL_tsp/kroE100.tsp",
	"./ALL_tsp/rl1889.tsp",
	"./ALL_tsp/rd400.tsp",
	"./ALL_tsp/pr152.tsp",
	"./ALL_tsp/ts225.tsp",
	"./ALL_tsp/nrw1379.tsp",
	"./ALL_tsp/u2152.tsp",
	"./ALL_tsp/d493.tsp",
	"./ALL_tsp/gr96.tsp",
	"./ALL_tsp/linhp318.tsp",
	"./ALL_tsp/ulysses22.tsp",
	"./ALL_tsp/u724.tsp",
	"./ALL_tsp/u159.tsp",
	"./ALL_tsp/pr226.tsp",
	"./ALL_tsp/gil262.tsp",
	"./ALL_tsp/u1060.tsp",
	"./ALL_tsp/kroC100.tsp",
	"./ALL_tsp/u574.tsp",
	"./ALL_tsp/u1817.tsp",
	"./ALL_tsp/lin105.tsp",
	"./ALL_tsp/fl417.tsp",
	"./ALL_tsp/gr137.tsp",
	"./ALL_tsp/dsj1000.tsp",
	"./ALL_tsp/ch150.tsp",
	"./ALL_tsp/d657.tsp",
]

instance_list, seed_list = evotoon.select_seeds(instance_list, 5, 765)

for a,b in zip(instance_list, seed_list):
	print(a,"--seed", b)